language: node_js
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - TYPESCRIPT=typescript@2.0

install:
  - npm install tslint --global

before_script: "echo starting"

script:
  - tslint *.ts

after_script: "echo done"